apiVersion: v1
kind: ConfigMap
metadata:
  name: galaxy-store-config
  namespace: default
data:
  APP_NAME: "Galaxy Store"
  APP_MODE: "production"
  MONGO_URL: "mongodb://mongo-service:27017/galaxydb"
